/**
 * Field Context — Phase 22A Working Memory snapshot.
 *
 * Captured by `buildFieldContextSnapshot` from the Phase 21 event stream,
 * rendered to markdown by `formatFieldContext`, and injected as a prefix
 * into agent prompts by agent-handlers.
 *
 * See docs/prd/phase-22a-working-memory.md for the full design.
 */

export interface FieldContextWorktree {
  id: string
  name: string
  branchName: string | null
}

export interface FieldContextFocusFile {
  path: string
  name: string
}

export interface FieldContextSelection {
  path: string
  fromLine: number
  toLine: number
  length: number
}

export interface FieldContextTerminalOutput {
  head: string
  tail: string
  truncated: boolean
  exitCode: number | null
}

export interface FieldContextLastTerminal {
  command: string
  commandAt: number
  /** Null if no `terminal.output` event was correlated to the command. */
  output: FieldContextTerminalOutput | null
}

export interface FieldContextActivityEntry {
  timestamp: number
  type: string
  /** One-line human-readable summary. Generated by the builder. */
  summary: string
}

export interface FieldContextSnapshot {
  /** Generation time (ms). Single clock used throughout the pipeline. */
  asOf: number
  /** Window size used when building (ms). */
  windowMs: number
  /** The worktree we built context for; null if the worktree was not found. */
  worktree: FieldContextWorktree | null
  /** User-authored notes from `worktrees.context`. */
  worktreeNotes: string | null
  /** Aggregated current focus derived from file.* events. */
  focus: {
    file: FieldContextFocusFile | null
    selection: FieldContextSelection | null
  }
  /** Most recent command + correlated output in the window, if any. */
  lastTerminal: FieldContextLastTerminal | null
  /** Remaining events in chronological order, deduped against structured sections. */
  recentActivity: FieldContextActivityEntry[]
}
